### ISSUE TITLE
Error: Invalid "each" attribute

### ISSUE THREAD

**Issue by ktedore** [seung-lab/CAVEpipelines#2]
Should be 

`disk_size_gb = each.value.disk_size_gb`

https://github.com/seung-lab/CAVEpipelines/blob/0bd0d78520aa668b1d67af730b7485cfb0cb69e4/terraform/pools.tf#L48

│ Error: Invalid "each" attribute
│ 
│   on pools.tf line 48, in resource "google_container_node_pool" "pool":
│   48:     disk_size_gb = each.disk_size_gb
│ 
│ The "each" object does not have an attribute named "disk_size_gb". The supported attributes are each.key and each.value, the current key and value pair of the
│ "for_each" attribute set.

**Comment by akhileshh** [comment]
done, thanks!
