### ISSUE TITLE
helm/example_values.yaml is missing

### ISSUE THREAD

**Issue by ktedore** [seung-lab/CAVEpipelines#3]

**Comment by akhileshh** [comment]
Thanks! Looks like I forgot to move the file and update paths after some restructure.

The correct path is `helm/pychunkedgraph/example_values.yml`

**Comment by akhileshh** [comment]
It was brought to my attention by @nkemnitz  that helm installation wasn't working, after inspection I realized `example_values.yaml` was incorrect.
I have updated it to reflect changes in the chart itself.
