### ISSUE TITLE
No resources available for main PCG pod

### ISSUE THREAD

**Issue by nkemnitz** [seung-lab/CAVEpipelines#8]
Usuually the main node pool is already scheduling `lX` and `tX` pods, leaving no resources for the scheduler pod, which is stuck in `Pending` state.

Maybe tainting the node pool for the l and t pods would help?

**Comment by akhileshh** [comment]
Something like [this](https://github.com/seung-lab/CAVEpipelines/blob/33abbf3a0c22fcfc141772ef145d87587ceb1459/helm/pychunkedgraph/example_values.yaml#L63)? 

Main node pool must not be used for `lX` pods though, they have their own [nodeSelector](https://github.com/seung-lab/CAVEpipelines/blob/33abbf3a0c22fcfc141772ef145d87587ceb1459/helm/pychunkedgraph/example_values.yaml#L101)

```
nodeSelector:
  cloud.google.com/gke-preemptible: "true"
```
this can be added to `tX` pods

**Comment by nkemnitz** [comment]
Will check again next time, but I thought I also saw `lX` pods on the main node pool...

**Comment by nkemnitz** [comment]
Could not replicate
